version: "3.1"

# The config recipe.
recipe: default.v1

# Identificador único de tu proyecto
assistant_id: 20241220-120951-chestnut-class

# Ajustamos el idioma a español
language: "es"

# Configuración del pipeline de NLU
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  
  # Segundo CountVectorsFeaturizer para análisis a nivel de caracteres
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true

  - name: EntitySynonymMapper

  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

  # Duckling configurado en español
  - name: DucklingEntityExtractor
    url: "http://localhost:8001"
    dimensions: ["time", "number", "amount-of-money", "distance"]
    locale: "es"
    timezone: "America/Buenos_Aires"

# Configuración de las políticas de diálogo
policies:
  - name: RulePolicy
  - name: MemoizationPolicy
  - name: TEDPolicy
